version: '3'

services:
  pg:
    image: postgres:15.3-alpine
    ports:
      - '${PG_DB_PORT}:5432'
    volumes:
      - ../../databases/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:6
    ports:
      - '${PG_ADMIN_PORT}:5050'
    volumes:
      - ../../databases/postgres/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    depends_on:
      - pg
