version: '3'

services:
  neo4j:
    image: neo4j:5.4.0
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ../../databases/neo4j/conf:/conf
      - ../../databases/neo4j/data:/data
      - ../../databases/neo4j/import:/import
      - ../../databases/neo4j/logs:/logs
      - ../../databases/neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_connector_bolt_listen__address: :7687
      NEO4J_dbms_connector_bolt_advertised__address: :7687
      NEO4J_dbms_connector_http_listen__address: :7474
      NEO4J_dbms_connector_http_advertised__address: :7474
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms.memory.heap.initial_size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G
