version: '3'

services:
  redis:
    image: 'redis:7-alpine'
    command: redis-server --requirepass ${REDIS_PASS:-password}
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  redis-insight:
    image: redislabs/redisinsight:1.13.1
    ports:
      - '6000:8001'
    volumes:
      - redis-insight-db:/db
    depends_on:
      - redis

volumes:
  redis-data:
    name: redis-data
  redis-conf:
    name: redis-conf
  redis-insight-db:
    name: redis-insight-db
